name: Vitest

on:
  - workflow_dispatch

jobs:
  docker:
    timeout-minutes: 15
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: node_modules-${{hashFiles('package-lock.json')}}
          restore-keys: node_modules-${{hashFiles('package-lock.json')}}

      - name: Npm install
        uses: ./.github/actions/npm-install

      - name: Run vitest
        uses: ./.github/actions/run-vitest
